### ISSUE TITLE
sy

### ISSUE THREAD

**Issue by hlugt** [bernmc/flashstor-trueNAS-fancontrol#1]
Hi, 
Thanks for your scripts. 
I have put it in a systemd unit as I find that easier to handle, also when needing to make changes and restart, and the logging goes to journald. 

<details>

<summary>temp-monitor.service</summary>

```
[Unit]
Description=ASUSTOR temp monitor fanspeed
Before=basic.target
After=local-fs.target sysinit.target
DefaultDependencies=no

[Service]
Type=simple
ExecStart=/bin/bash /home/admin/temp_monitor.sh
Restart=on-failure
RestartSec=10
KillMode=mixed

[Install]
WantedBy=basic.target

```
</details>

Also want to point out a typo in line 265: you use the hdd_desired_pwm instead of the sys_desired_pwm variable.
```
     if [[ $sys_desired_pwm -gt 255 ]] ; then
          # over max - truncate to max
          hdd_desired_pwm=255
     fi

```

**Comment by bernmc** [comment]
thanks - typo fixed
Which version of TrueNAS are you using?

**Comment by hlugt** [comment]
Hi I am using cobia. Why?

**Comment by bernmc** [comment]
Just keeping track of what works on what (I'm still on bluefin) - just did a temp setup of cobia to check requirements for fan control.

**Comment by hlugt** [comment]
Ah ok. I have an AS6706T and indeed cobia works. Pity you have to do the install-dev thingy...
