### ISSUE TITLE
24.04-RC.1

### ISSUE THREAD

**Issue by phgarman** [bernmc/flashstor-trueNAS-fancontrol#4]
I see the information regarding 23.x, but was wanting to run the latest developmental branch (24.04-RC.1).  Are the caveats and notes similar to 23.x?

**Comment by bernmc** [comment]
I haven't had a chance to try the latest versions of TrueNAS (I'm still on 22.x with a 'if it ain't broke, don't fix it' attitude ;) ). You should have a look at issue #3 as well before trying it out.
I would assume that each iteration will be slightly more locked down, but developer mode should still unlock things as iX need developers to tweak the thing.

**Comment by bernmc** [comment]
Update - see issue #3 - works with dragonfish, but currently NOT with Electric eel RC's.

I'll close this as it relates to dragonsfish.

**Comment by bernmc** [comment]
closed
